CIS174CourseWebsite/Controllers/AssignmentController.cs
/***************************************************************
* Name        : AssignmentController.cs
* Author      : Tom Sorteberg
* Created     : 02/14/2021
* Course      : CIS 174
* Version     : 1.0
* OS          : Windows 10 Pro, Visual Studio Community 2019
* Copyright   : This is my own original work based on
*               specifications issued by our instructor
* Description : Module 4 Topic 5
* I have not used unauthorized source code, either modified or 
* unmodified. I have not given other fellow student(s) access 
* to my program.         
***************************************************************/
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using CIS174CourseWebsite.Models;
using System.Collections.Generic;

namespace MultiPageWebApp.Controllers
{
    public class AssignmentController : Controller
    {
        // Context class private attribute.
        private AssignmentContext context { get; set; }

        // Primary contructor.
        public AssignmentController(AssignmentContext ctx)
        {
            context = ctx;
        }

        // Index action.
        public IActionResult List()
        {
            var assignments = context.Assignments.OrderBy(m => m.Name).ToList();
            ViewBag.Assignments = new List<Assignment>(assignments);
            return View(assignments);
        }
    }
}

CIS174CourseWebsite/Areas/M4T5/Views/Shared/_Layout.cshtml
<!--
/***************************************************************
* Name        : _Layout.cshtml
* Author      : Tom Sorteberg
* Created     : 02/14/2021
* Course      : CIS 174
* Version     : 1.0
* OS          : Windows 10 Pro, Visual Studio Community 2019
* Copyright   : This is my own original work based on
*               specifications issued by our instructor
* Description : Module 4 Topic 5
* I have not used unauthorized source code, either modified or
* unmodified. I have not given other fellow student(s) access
* to my program.
***************************************************************/
-->
@{
    string controller = ViewContext.RouteData.Values["controller"].ToString();
    string action = ViewContext.RouteData.Values["action"].ToString();

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - CIS174CourseWebsite</title>
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
                <a asp-area="" controller="Home" asp-action="Index" class="navbar-brand">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Assignment" asp-action="List" class="nav-link">Assignment Page</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Assignments Quicklinks</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @foreach (var assignment in ViewBag.Assignments)
                                {
                                    <a class="dropdown-item" href="@assignment.URL">@assignment.Name</a>
                                }
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        @RenderBody()

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Tom Sorteberg
        </div>
    </footer>

</body>
</html>